# Generated by Django 5.2.17 on 2026-09-30 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, help_text='Auto-generated if left blank — share this with students to join.', max_length=20, unique=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('max_students', models.PositiveIntegerField(blank=True, help_text='License cap — leave blank for unlimited.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(blank=True, help_text="The user who can view this institution's dashboard.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_institutions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
