# Generated by Django 5.2.17 on 2026-09-30 16:07

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentAffair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('national', 'National'), ('international', 'International'), ('sports', 'Sports'), ('economy', 'Economy'), ('science', 'Science & Technology'), ('awards', 'Awards & Honours')], default='national', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='current_affairs/', validators=[core.validators.validate_image_size])),
                ('source_link', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True, help_text='Admin approval to go live. Combined with "Publish at" below for scheduling.')),
                ('publish_at', models.DateTimeField(blank=True, help_text='Optional — set a future date/time to schedule this. Leave blank to publish immediately once "Is published" is checked.', null=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'is_published'], name='idx_affair_date_published')],
            },
        ),
        migrations.CreateModel(
            name='DailyQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('questions', models.ManyToManyField(blank=True, related_name='daily_quizzes', to='questions.question')),
            ],
        ),
    ]
