# Generated by Django 5.2.17 on 2026-09-30 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('avg_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('weak_topics', models.TextField(blank=True, help_text='Comma-separated tag names with low accuracy')),
                ('strong_topics', models.TextField(blank=True, help_text='Comma-separated tag names with high accuracy')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='exams.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Performance Analytics',
                'unique_together': {('user', 'subject')},
            },
        ),
    ]
