# Generated by Django 5.2.17 on 2026-09-30 16:07

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='study_material/', validators=[core.validators.validate_document_size])),
                ('material_type', models.CharField(choices=[('pdf', 'PDF Notes'), ('notes', 'Notes'), ('pyq', 'Previous Year Question Paper')], default='pdf', max_length=10)),
                ('is_premium', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_materials', to='exams.subject')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('video_url', models.URLField()),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duration in minutes')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumbnails/', validators=[core.validators.validate_image_size])),
                ('is_premium', models.BooleanField(default=False)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_lectures', to='exams.subject')),
            ],
        ),
    ]
